# Install Dymola 2021 on Ubuntu 18.04 LTS, starting from scratch at
# https://app.vagrantup.com/hashicorp/boxes/bionic64 using VirtualBox

---
- hosts: all  # 'all' works with Vagrant but not in general
  vars:
    vm_hostname: "ms-vm-ubuntu1804"
    # List of packages/libraries to be installed as .rpm-file/as .deb-file
    list_of_packages:
      - { rpm: "dymola-2021.1-1.x86_64.rpm", deb: "dymola_2021.1-1_amd64.deb" }
      - { rpm: "dymola-dassaultsystemes-2021.1-1.x86_64.rpm", deb: "dymola-dassaultsystemes_2021.1-1_amd64.deb" }
      - { rpm: "dymola-electrifiedpowertrains-2021.1-1.x86_64.rpm", deb: "dymola-electrifiedpowertrains_2021.1-1_amd64.deb" }
    # Disable GNOME default folders in $HOME (`true`) or let them be (`false`)
    disable_gnome_default_folders: true
  handlers:
    - name: restart network manager
      service:
        name: network-manager
        state: restarted
      become: true
    - name: netplan apply
      command:
        cmd: "netplan apply"
      become: true
  tasks:
    # https://docs.ansible.com/ansible/latest/modules/apt_module.html
    - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: true

    # https://wiki.ubuntuusers.de/GNOME_Installation
    - name: Install GNOME core
      apt:
        name: gnome-core
        state: present
      become: true

    # CAREFUL, this broke automatic resizing of the VM screen size until re-installing
    # the VirtualBox Guest Additions (might work on first install, though)
    - name: "Perform update using `apt-get dist-upgrade`"  # https://askubuntu.com/a/81594
      apt:
        upgrade: dist
      become: true

    - name: "Set hostname to {{ vm_hostname }}"
      hostname:
        name: "{{ vm_hostname }}"
      become: true

    #   become: true

    # Get rid of annoying default folders in $HOME created by GNOME
    - name: Disable default folders
      replace:
        dest: "/home/{{ ansible_user }}/.config/user-dirs.dirs"
        regexp: "^(XDG_.*)$"
        replace: '# \1'
      when: disable_gnome_default_folders
    - name: Make disabling of default folders persistent
      lineinfile:
        dest: "/home/{{ ansible_user }}/.config/user-dirs.conf"
        regexp: '^enabled='
        line: "enabled=false"
        create: yes
        state: present
      when: disable_gnome_default_folders
    - name: Remove folders created during installation
      file:
        path: "/home/{{ ansible_user }}/{{ item }}"
        state: absent
      loop:
        - "Desktop"
        - "Documents"
        - "Downloads"
        - "Music"
        - "Pictures"
        - "Public"
        - "Templates"
        - "Videos"
      when: disable_gnome_default_folders

    # https://askubuntu.com/a/1043244
    - name: Enable wired network connection, part 1
      lineinfile:
        dest: "/etc/NetworkManager/NetworkManager.conf"
        regexp: '^managed='
        line: "managed=true"
        state: present
      become: true
      notify: restart network manager

    # https://askubuntu.com/a/1178044
    - name: Enable wired network connection, part 2
      lineinfile:
        dest: "/etc/netplan/01-netcfg.yaml"
        regexp: '^\s\srenderer:'
        line: "  renderer: NetworkManager"
        state: present
      become: true
      notify: netplan apply

    # Install Dymola 2021 ################################################################
    # Find missing packages at https://packages.ubuntu.com/ (limit search to "bionic")
    - name: Install dependencies of Dymola 2021
      apt:
        name:
          - alien  # for converting .rpm-packages to .deb-packages
          - zip  # for FMU export (according to Dymola manual)
          - unzip  # for FMU export (according to Dymola manual)
          - g++-multilib  # for 32-bit compilation (according to Dymola manual)
          - libc6-dev-i386  # for 32-bit compilation (according to Dymola manual)
          # failure during conversion to .deb: `libQt5Gui.so.5 needed`
          # --> install `libqt5gui5`
          - libqt5gui5
          # /opt/dymola-2021-x86_64/bin64/dymola: error while loading shared libraries:
          # libGLU.so.1: cannot open shared object file: No such file or directory
          # --> install `libglu1-mesa`
          - libglu1-mesa
          # /opt/dymola-2021-x86_64/bin64/dymola: error while loading shared libraries:
          # libsnappy.so.1: cannot open shared object file: No such file or directory
          # --> install `libsnappy1v5`
          - libsnappy1v5
        state: present
      become: true

    - name: Convert .rpm-packages to .deb-packages
      command:
        chdir: "/vagrant/linux_x86_64/"  # directory containing .rpm-packages
        cmd: "alien --scripts --keep-version ./{{ item.rpm }}"
        creates: "./{{ item.deb }}"
      loop: "{{ list_of_packages|flatten(levels=1) }}"

    - name: Install Dymola and libraries
      apt:
        deb: "/vagrant/linux_x86_64/{{ item.deb }}"  # directory containing .deb-packages
        state: present
      loop: "{{ list_of_packages|flatten(levels=1) }}"
      become: true

    - name: Apply patch
      copy:
        src: ./libevent-2.0.so.5  # path to library on host-OS
        dest: /opt/dymola-2021-x86_64/bin/lib64/libevent-2.0.so.5
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0777'  # '0777' is probably excessive.. no idea what's required, though

    # Voilà! It should now be possible to start Dymola 2021 as `dymola` from the terminal
    # Bonus: Make Dymola 2021 accessible from the Applications-menu in GNOME
    - name: Install .desktop-file for Dymola
      copy:
        src: ./desktopfile.txt
        dest: "/home/{{ ansible_user }}/.local/share/applications/dymola.desktop"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0775'
